### ISSUE TITLE
Tests occasionally fail when run repeatedly

### ISSUE THREAD

**Issue by dhood** [ament/uncrustify#16]
When the tests for this package are run multiple times, occasionally tests start to fail.
http://ci.ros2.org/job/nightly_win_rep/625/testReport/junit/projectroot/tests/test_uncrustify/ failed on the 20th time with test file [02431](https://github.com/uncrustify/uncrustify/blob/7e23e9d1ffefd778733fc4502452b67a1363c0ae/tests/c.test#L283) and http://ci.ros2.org/job/nightly_win_rep/629/testReport/junit/projectroot/tests/test_uncrustify/ failed on the 13th time with test file [01021](https://github.com/uncrustify/uncrustify/blob/7e23e9d1ffefd778733fc4502452b67a1363c0ae/tests/c.test#L221)

I've only seen this happen on windows. Given [the line at which it fails](https://github.com/uncrustify/uncrustify/blob/6dc0da0e2671b4a26df57a26eaed0eacbdf5e829/tests/run_tests.py#L136) I would think it's an I/O error and not the linter itself.

**Comment by dirk-thomas** [comment]
Since the problem happened on a Windows machine it is more likely that a Windows service like Defender is holding a lock on that file. Until there is an incident where this happens on a non-Windows machine I will close this and reopen the original ticket again.
